# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7
    container_name: db_test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: loren
      MYSQL_DATABASE: projeto_vaga_backend
      MYSQL_USER: loren
      MYSQL_PASSWORD: loren # PÔR ENVS
    ports:
      - "3306:3306"
    volumes:
      - ./src/infra/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  api:
    restart: 'always'
    build: 
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ./entrypoint.sh
    expose:
      - 8000