version: '3.8'

services:

  postgres:
    image: postgres:16
    restart: always
    container_name: db_test
    environment:
      POSTGRES_PASSWORD: loren
      POSTGRES_DB: projeto_vaga_backend
      POSTGRES_USER: loren
    ports:
      - "5432:5432"


  # api:
  #   restart: 'always'
  #   build: 
  #     context: .
  #     dockerfile: ./Dockerfile
  #   entrypoint: ./entrypoint.sh
  #   volumes:
  #     - ./src:/app/src:Z
  #   env_file:
  #     - .env.example
  #   ports:
  #     - "8000:8000"
