# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: loren
      MYSQL_DATABASE: projeto_vaga_backend
      MYSQL_USER: loren
      MYSQL_PASSWORD: loren
    ports:
      - "3306:3306"
    volumes:
      - ./src/utils/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    

  web:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db